version: "3"

tasks:
  generate:
  aliases:
    - gen
  desc: "Generate code from proto files"  
  cmds:
    - protoc -I proto proto/geo.proto --go_out=./gen/geogrpc --go_opt=paths=source_relative --go-grpc_out=./gen/geogrpc --go-grpc_opt=paths=source_relative
