version: '3'

services:
  hugo:
    image: klakegg/hugo:0.101.0-ext-alpine
    container_name: hugo
    command: server --bind "0.0.0.0" 
    volumes:
      - "./hugo:/src"
    ports:
      - "1313:1313"
    # networks:
    #   - mylocal

  proxy:
    restart: on-failure
    container_name: proxy
    build: ./proxy
    command: ./main
    volumes:
      - "./hugo/content:/app/static"
    ports:
      - "8080:8080"
      - "6060:6060"
      # - "9090:9090"
    environment:
      DB_DRIVER: ${DB_DRIVER}  
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres 
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}       
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"    

  migrator:
    image: migrate/migrate
    volumes:
      - ./proxy/migrations:/migrations 
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable",
      ]    
    command: ["up"]   
    depends_on:
      - db
    restart: on-failure
    
  redis:
    image: redis
    container_name: redis
    ports:
      - "6378:6378"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  

  grafana1:
    image: ldmitryld/grafana:latest
    ports:
      - "3000:3000"    
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:       
  
# networks:
#   mypprof:
#     driver: bridge
   
      
